# Generated by Django 5.0.7 on 2024-08-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tododata',
            table='todo_table',
        ),
    ]
